apiVersion: skaffold/v1
kind: Config
metadata:
  name: ingress.controller
build:
  artifacts:
    - image: justincr.azurecr.io/ingresscontroller
      context: src/
    - image: justincr.azurecr.io/hello-aspnetcore
      context: samples/BackendApp/
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - kubernetes-profiles/ingress-controller-deployment.yml
      - kubernetes-profiles/ingress-controller-service.yml
      - kubernetes-profiles/backend-deployment.yml
      - kubernetes-profiles/backend-service.yml
      - kubernetes-profiles/ingress.yml
