apiVersion: skaffold/v1
kind: Config
metadata:
  name: kubetest
build:
  artifacts:
    - image: justincr.azurecr.io/hello-aspnetcore
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - deployment.yml
      - service.yml
